import type { Dashboard as Data, Page } from '../domain';
export function Dashboard({data,page,onInspect,exportMode=false}:{data:Data;page:Page;onInspect?:(id:string)=>void;exportMode?:boolean}){
  const renderRow=(row:any)=><button type="button" className="metric-row" key={row.id} onClick={()=>onInspect?.(row.id)} disabled={!onInspect} aria-label={`Inspect ${row.label}`}><span className={`metric-value coral ${row.leader==='left'?'leading':''}`}>{row.left.display}{row.leader==='left'&&<i/>}</span><span className="metric-label">{row.label}<small>{row.unit||'within coverage'}</small></span><span className={`metric-value mint ${row.leader==='right'?'leading':''}`}>{row.leader==='right'&&<i/>}{row.right.display}</span></button>;
  return <article className={`dashboard page-${page} ${exportMode?'export-canvas':''}`} data-export-ready="true">
    <header className="poster-header"><span className="poster-brand">L<span> / </span> LEGEND</span><span>THE COMPARISON SERIES <b>№ 001</b></span></header>
    <div className="poster-heading"><div className="eyebrow">{data.freshness} / {data.kind==='demo'?'SYNTHETIC DEMONSTRATION':'VALIDATED SNAPSHOT'}</div><h1>TWO LEGENDS.<br/><span>ONE PERSPECTIVE.</span></h1><p>{page==='overview'?'Career overview':'Goal efficiency'} <span> / </span> {data.freshness==='B0'?'Career within benchmark coverage':'Current-season coverage'}</p></div>
    <div className="contenders">{data.players.map((p,i)=><div key={p.id} className={`contender ${p.accent}`}><div className="player-art"><span className="player-number">{p.number}</span><span className="monogram">{p.initials}</span><div className="art-lines"/><span className="player-label">PLAYER {String(i+1).padStart(2,'0')}</span></div><span className="country">{p.country}</span><h2>{p.name.split(' ').slice(0,-1).join(' ')}<strong>{p.name.split(' ').at(-1)}</strong></h2></div>)}<span className="versus">VS</span></div>
    {data.kind==='demo'&&<div className="demo-strip">DEMO DATA <span>Invented values · not actual player statistics</span></div>}
    {page==='international'?<div className="metric-section international-section"><div className="metric-section-title"><span>03 / INTERNATIONAL PERFORMANCE</span><span>THE NUMBERS</span></div>{data.pages.international.map(group=><section className="international-group" key={group.id}><div className="international-group-heading"><b>{group.label}</b><small>{group.description}</small></div>{group.rows.map(renderRow)}</section>)}</div>:<div className="metric-section"><div className="metric-section-title"><span>{page==='overview'?'01 / CAREER OVERVIEW':'02 / GOAL EFFICIENCY'}</span><span>THE NUMBERS</span></div>{data.pages[page].map(renderRow)}</div>}
    <div className="poster-note"><span className="note-mark">↗</span><p>{page==='overview'?'Every number has a story. Every story needs a source.':page==='efficiency'?'Production meets precision. Compare the rate, then explore the context.':'International records grouped by the declared competition taxonomy.'}</p></div>
    <footer className="poster-footer"><div><b>{data.snapshotId}</b><span>Cutoff {data.cutoffAt.slice(0,10)} · {data.cutoffAt.slice(11,16)} UTC exclusive</span></div><div><b>LEGEND.STUDIO</b><span>{data.coverage.policy==='completed_editions'?'Completed editions only':'Season-specific coverage'}</span></div></footer>
    <div className="poster-exclusions">{data.coverage.exclusions.join(' ')}</div>
  </article>;
}
