export type MetricId = 'appearances' | 'goals' | 'assists' | 'minutes' | 'penalty_goals' | 'club_trophies' | 'international_trophies' | 'awards';
export interface Player { id: string; name: string; country: string; initials: string; number: number; accent: 'coral' | 'mint' }
export interface Source { id: string; provider: 'fixture' | 'rsssf' | 'transfermarkt' | 'api-football'; url: string; retrievedAt: string; attribution: string; documentHash: string }
export type InternationalCategory = 'overall' | 'friendly' | 'world_cup' | 'continental' | 'qualifier' | 'other';
export interface Observation { playerId: string; metric: MetricId; category?: InternationalCategory; value: number | null; scopeId: string; matchSetId: string; definitionVersion: 'v1'; coverage: 'complete' | 'partial' | 'unknown'; sourceIds: string[]; review: 'accepted' | 'pending' | 'rejected'; reviewReason: string }
export interface Manifest { id: string; scopeId: string; policy: 'completed_editions' | 'current_season'; cutoffAt: string; editions: {competition: string; season: string; status: 'completed' | 'in_progress'; matchSetId: string; startAt?:string;endAt?:string;matchSetHash?:string}[]; exclusions: string[]; validated: boolean }
export interface Snapshot { id: string; label: string; freshness: 'B0' | 'B1'; kind: 'demo' | 'verified'; publishedAt: string; manifest: Manifest; players: Player[]; sources: Source[]; observations: Observation[] }
export type Page = 'overview' | 'efficiency' | 'international';
export interface MetricValue { value: {numerator: string; denominator: string} | null; display: string; status: 'available' | 'unavailable' | 'undefined' | 'invalid'; reason: string | null; sourceIds: string[] }
export interface MetricRow { id: string; label: string; formula: string; unit: string; direction: 'higher' | 'lower'; left: MetricValue; right: MetricValue; leader: 'left' | 'right' | null; comparison: string }
export interface InternationalGroup { id: InternationalCategory; label: string; description: string; rows: MetricRow[] }
export interface Dashboard { id: string; createdAt: string; snapshotId: string; label: string; freshness: 'B0' | 'B1'; kind: 'demo' | 'verified'; scopeId: string; cutoffAt: string; coverage: Manifest; definitionVersion: 'v1'; rendererVersion: 'v1'; players: Player[]; sources: Source[]; pages: {overview: MetricRow[]; efficiency: MetricRow[]; international: InternationalGroup[]}; narrative: string }
