import type { MetricId, Snapshot } from '../domain.ts';
import { Store } from '../storage/index.ts';
export const demoEvidence='SYNTHETIC TEST FIXTURE. All numerical values are invented for software testing, not football statistics.';
export function demoSnapshot(documentHash:string):Snapshot {
  const players=[{id:'cristiano_ronaldo',name:'Cristiano Ronaldo',country:'Portugal',initials:'CR',number:7,accent:'coral' as const},{id:'lionel_messi',name:'Lionel Messi',country:'Argentina',initials:'LM',number:10,accent:'mint' as const}];
  const data:Record<MetricId,number|null>[]=[{appearances:120,goals:90,assists:24,minutes:9900,penalty_goals:15,club_trophies:null,international_trophies:null,awards:null},{appearances:110,goals:88,assists:40,minutes:8800,penalty_goals:10,club_trophies:null,international_trophies:null,awards:null}];
  return {id:'DEMO_2025_26_V1',label:'2025/26 · Demo benchmark',freshness:'B0',kind:'demo',publishedAt:'2026-07-02T12:00:00Z',manifest:{id:'DEMO_COVERAGE_V1',scopeId:'synthetic_senior_v1',policy:'completed_editions',cutoffAt:'2026-07-01T00:00:00Z',editions:[{competition:'Synthetic sample matches',season:'2025/26',status:'completed',matchSetId:'demo_matches_v1'}],exclusions:['All values are synthetic examples, not actual player statistics.','Trophies and awards have no fixture evidence and remain unavailable.'],validated:true},players,sources:[{id:'demo_fixture',provider:'fixture',url:'fixture://cr7-vs-messi',retrievedAt:'2026-07-02T12:00:00Z',attribution:'Legend software test fixture — not factual sports data',documentHash}],observations:players.flatMap((p,i)=>Object.entries(data[i]).map(([metric,value])=>({playerId:p.id,metric:metric as MetricId,value,scopeId:'synthetic_senior_v1',matchSetId:'demo_matches_v1',definitionVersion:'v1',coverage:value===null?'unknown':'complete',sourceIds:['demo_fixture'],review:'accepted',reviewReason:'Synthetic fixture for deterministic-engine testing only'})))};
}
export function seedDemo(store:Store){const digest=store.preserve(demoEvidence);if(!store.listSnapshots().some(s=>s.id==='DEMO_2025_26_V1'))store.publish(demoSnapshot(digest),'demo');}
